import { useEffect, useState } from "react";
import { Activity, AlertTriangle, Bot, Gamepad2, LogOut, Menu, MessageSquare, RefreshCw, Settings, ShieldCheck, Users, X } from "lucide-react";
import { supabase } from "./lib/supabase";

type Page="dashboard"|"monitor"|"questions"|"games"|"errors"|"settings";
const nav=[["dashboard","Dashboard",Bot],["monitor","Monitor",Activity],["questions","Questions",MessageSquare],["games","Games",Gamepad2],["errors","Errors",AlertTriangle],["settings","Settings",Settings]] as const;

function Login({onLoggedIn}:{onLoggedIn:()=>void}){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const r=await supabase.auth.signInWithPassword({email,password});if(r.error)setError(r.error.message);else onLoggedIn();setBusy(false)}
return <main className="login"><form className="login-card" onSubmit={submit}><div className="brand"><Bot size={30}/><div><strong>UzzapBot</strong><span>Control Center</span></div></div><h1>Administrator Login</h1><p>Sign in to monitor UzzapBot.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?"Signing in...":"Sign in"}</button></form></main>}

function App(){const[session,setSession]=useState<any>(null),[page,setPage]=useState<Page>("dashboard"),[mobile,setMobile]=useState(false),[checking,setChecking]=useState(true);
useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setChecking(false)});const x=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>x.data.subscription.unsubscribe()},[]);
if(checking)return <div className="loading">Loading...</div>;if(!session)return <Login onLoggedIn={()=>supabase.auth.getSession().then(({data})=>setSession(data.session))}/>;
const title=nav.find(n=>n[0]===page)?.[1]||"Dashboard";
return <div className="app"><aside className={mobile?"sidebar open":"sidebar"}><div className="brand"><Bot size={28}/><div><strong>UzzapBot</strong><span>Control Center</span></div></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?"nav active":"nav"} onClick={()=>{setPage(id);setMobile(false)}}><Icon size={18}/>{label}</button>)}</nav><button className="nav logout" onClick={()=>supabase.auth.signOut()}><LogOut size={18}/>Logout</button></aside>{mobile&&<button className="backdrop" onClick={()=>setMobile(false)}><X/></button>}<section className="content"><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div><h1>{title}</h1><span>Production UzzapBot management</span></div><div className="online"><i/> Supabase</div></header>{page==="dashboard"&&<Dashboard/>}{page==="monitor"&&<Monitor/>}{page==="questions"&&<Questions/>}{page==="games"&&<Games/>}{page==="errors"&&<Errors/>}{page==="settings"&&<SettingsPage/>}</section></div>}

function Stat({label,value,icon:Icon}:{label:string;value:string;icon:any}){return <div className="card"><div className="card-icon"><Icon size={19}/></div><div><span>{label}</span><strong>{value}</strong></div></div>}
function Dashboard(){const[s,setS]=useState({processed:0,failed:0,games:0,players:0});const load=async()=>{const r=await Promise.all([supabase.from("uzzapbot_event_receipts").select("*",{count:"exact",head:true}).eq("status","processed"),supabase.from("uzzapbot_event_receipts").select("*",{count:"exact",head:true}).eq("status","failed"),supabase.from("game_sessions").select("*",{count:"exact",head:true}),supabase.from("game_players").select("*",{count:"exact",head:true})]);setS({processed:r[0].count||0,failed:r[1].count||0,games:r[2].count||0,players:r[3].count||0})};useEffect(()=>{load()},[]);
return <><div className="toolbar"><div><h2>Overview</h2><p>Live read-only view of the production bot backend.</p></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div><div className="grid"><Stat label="Bot Runtime" value="Edge Function" icon={Bot}/><Stat label="Processed Events" value={String(s.processed)} icon={Activity}/><Stat label="Failed Events" value={String(s.failed)} icon={AlertTriangle}/><Stat label="Game Sessions" value={String(s.games)} icon={Gamepad2}/><Stat label="Players" value={String(s.players)} icon={Users}/><Stat label="Admin Access" value="Protected" icon={ShieldCheck}/></div><RecentEvents/></>}

function RecentEvents(){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.from("uzzapbot_event_receipts").select("message_id,received_at,processed_at,status,error_text").order("received_at",{ascending:false}).limit(12).then(({data})=>setRows(data||[]))},[]);return <div className="panel"><h2>Recent Bot Events</h2><div className="table-wrap"><table><thead><tr><th>ID</th><th>Received</th><th>Status</th><th>Latency</th><th>Error</th></tr></thead><tbody>{rows.map(r=><tr key={r.message_id}><td>{r.message_id}</td><td>{new Date(r.received_at).toLocaleString()}</td><td><b className={"badge "+r.status}>{r.status}</b></td><td>{r.processed_at?String(Math.max(0,new Date(r.processed_at).getTime()-new Date(r.received_at).getTime()))+" ms":"-"}</td><td>{r.error_text||"-"}</td></tr>)}{!rows.length&&<tr><td colSpan={5}>No events found.</td></tr>}</tbody></table></div></div>}

function Monitor(){const[rows,setRows]=useState<any[]>([]);const load=async()=>{const r=await supabase.from("uzzapbot_event_receipts").select("message_id,received_at,processed_at,status,error_text").order("received_at",{ascending:false}).limit(50);setRows(r.data||[])};useEffect(()=>{load()},[]);return <div className="panel"><div className="toolbar"><div><h2>Event Monitor</h2><p>Durable UzzapBot event receipts.</p></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div><div className="table-wrap"><table><thead><tr><th>Message ID</th><th>Received</th><th>Processed</th><th>Status</th><th>Error</th></tr></thead><tbody>{rows.map(r=><tr key={r.message_id}><td>{r.message_id}</td><td>{new Date(r.received_at).toLocaleString()}</td><td>{r.processed_at?new Date(r.processed_at).toLocaleString():"-"}</td><td><b className={"badge "+r.status}>{r.status}</b></td><td>{r.error_text||"-"}</td></tr>)}</tbody></table></div></div>}

function Questions(){
 const[rows,setRows]=useState<any[]>([]),[busy,setBusy]=useState(true),[form,setForm]=useState({category:"trivia",question:"",answer:"",aliases:"",points:"10",difficulty:"normal"}),[msg,setMsg]=useState("");
 const load=async()=>{setBusy(true);const r=await supabase.from("uzzapbot_questions").select("*").order("created_at",{ascending:false}).limit(100);setRows(r.data||[]);setBusy(false)};useEffect(()=>{load()},[]);
 const add=async(e:React.FormEvent)=>{e.preventDefault();setMsg("");const aliases=form.aliases.split(",").map(x=>x.trim()).filter(Boolean);const v=await supabase.rpc("uzzapbot_question_validation",{p_question:form.question.trim(),p_answer:form.answer.trim(),p_aliases:aliases,p_category:form.category});if(v.error){setMsg(v.error.message);return}const check=v.data as any;const r=await supabase.from("uzzapbot_questions").insert({category:form.category,question:form.question.trim(),answer:form.answer.trim(),aliases,points:Number(form.points),difficulty:form.difficulty,status:"draft",verification_score:check?.score??0,duplicate_of:check?.duplicate_of??null,verification_notes:(check?.issues||[]).join("; ")});if(r.error)setMsg(r.error.message);else{setMsg("Draft saved. Verification: "+(check?.score??0)+"/100"+((check?.issues||[]).length?" — "+check.issues.join("; "):"."));setForm({...form,question:"",answer:"",aliases:""});load()}};
 const setStatus=async(id:number,status:string)=>{const r=await supabase.from("uzzapbot_questions").update({status,reviewed_at:status==="approved"||status==="rejected"?new Date().toISOString():null}).eq("id",id);if(r.error)setMsg(r.error.message);else load()};
 return <><div className="panel"><div className="toolbar"><div><h2>Question Bank</h2><p>Admin-managed questions with verification status.</p></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div><form className="question-form" onSubmit={add}><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>trivia</option><option>anime</option><option>logic</option><option>gta</option><option>english</option><option>tagalog</option><option>math</option></select><input placeholder="Question" value={form.question} onChange={e=>setForm({...form,question:e.target.value})} required/><input placeholder="Correct answer" value={form.answer} onChange={e=>setForm({...form,answer:e.target.value})} required/><input placeholder="Aliases, comma separated" value={form.aliases} onChange={e=>setForm({...form,aliases:e.target.value})}/><input type="number" min="1" max="1000" value={form.points} onChange={e=>setForm({...form,points:e.target.value})}/><select value={form.difficulty} onChange={e=>setForm({...form,difficulty:e.target.value})}><option>easy</option><option>normal</option><option>hard</option></select><button className="primary" type="submit">Add Draft</button></form>{msg&&<div className="notice">{msg}</div>}</div><div className="panel"><h2>Verification Queue</h2>{busy?<p>Loading...</p>:<div className="table-wrap"><table><thead><tr><th>Category</th><th>Question</th><th>Answer</th><th>Difficulty</th><th>Score</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(q=><tr key={q.id}><td>{q.category}</td><td>{q.question}</td><td>{q.answer}</td><td>{q.difficulty}</td><td>{q.verification_score??"-"}/100{q.duplicate_of?" · duplicate #"+q.duplicate_of:""}</td><td><b className={"badge "+(q.status==="approved"?"processed":q.status==="rejected"?"failed":"received")}>{q.status}</b></td><td><div className="actions">{q.status!=="approved"&&<button className="mini approve" onClick={()=>setStatus(q.id,"approved")}>Approve</button>}{q.status!=="rejected"&&<button className="mini reject" onClick={()=>setStatus(q.id,"rejected")}>Reject</button>}</div></td></tr>)}{!rows.length&&<tr><td colSpan={7}>No questions yet.</td></tr>}</tbody></table></div>}</div></>
}
function Games(){const[games,setGames]=useState<any[]>([]);useEffect(()=>{supabase.from("game_sessions").select("room_name,game,mode,question_number,points,limit_count,paused,updated_at").order("updated_at",{ascending:false}).limit(50).then(({data})=>setGames(data||[]))},[]);return <div className="panel"><h2>Game Sessions</h2><div className="table-wrap"><table><thead><tr><th>Room</th><th>Game</th><th>Mode</th><th>Q#</th><th>Points</th><th>Limit</th><th>Paused</th><th>Updated</th></tr></thead><tbody>{games.map(g=><tr key={g.room_name}><td>{g.room_name}</td><td>{g.game}</td><td>{g.mode}</td><td>{g.question_number}</td><td>{g.points}</td><td>{g.limit_count}</td><td>{g.paused?"Yes":"No"}</td><td>{new Date(g.updated_at).toLocaleString()}</td></tr>)}{!games.length&&<tr><td colSpan={8}>No active game sessions found.</td></tr>}</tbody></table></div></div>}
function Errors(){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.from("uzzapbot_event_receipts").select("message_id,received_at,error_text").eq("status","failed").order("received_at",{ascending:false}).limit(50).then(({data})=>setRows(data||[]))},[]);return <div className="panel"><h2>Error Center</h2><p>Failed production events. The dashboard does not automatically retry events.</p><div className="table-wrap"><table><thead><tr><th>Message ID</th><th>Time</th><th>Error</th></tr></thead><tbody>{rows.map(r=><tr key={r.message_id}><td>{r.message_id}</td><td>{new Date(r.received_at).toLocaleString()}</td><td>{r.error_text||"Unknown error"}</td></tr>)}{!rows.length&&<tr><td colSpan={3}>No failed events.</td></tr>}</tbody></table></div></div>}
function SettingsPage(){return <div className="panel"><h2>Production Settings</h2><p>Read-only foundation. Service-role credentials are never stored in the browser.</p><div className="setting"><span>Supabase project</span><b>hrjgblvxhtbopuyzyasu</b></div><div className="setting"><span>Bot runtime</span><b>Supabase Edge Function: uzzapbot</b></div><div className="setting"><span>Question source</span><b>Edge Function datasets</b></div></div>}
export default App;
