import { useEffect, useState } from "react";
import { Activity, AlertTriangle, Bot, Gamepad2, Gauge, HelpCircle, BookOpen, Clock, LogOut, Menu, MessageSquare, RefreshCw, Settings, ShieldCheck, Users, X } from "lucide-react";
import { supabase } from "./lib/supabase";

type Page="dashboard"|"control"|"rooms"|"players"|"monitor"|"questions"|"games"|"errors"|"performance"|"settings";
const nav=[["dashboard","Dashboard",Bot],["control","Game Control",Gamepad2],["rooms","Rooms",ShieldCheck],["players","Players",Users],["monitor","Monitor",Activity],["questions","Questions",MessageSquare],["games","Games",Gamepad2],["performance","Performance",Gauge],["errors","Errors",AlertTriangle],["settings","Settings",Settings]] as const;

function Login({onLoggedIn}:{onLoggedIn:()=>void}){const[email,setEmail]=useState("mharbalaba@gmail.com"),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const r=await supabase.auth.signInWithPassword({email,password});if(r.error)setError(r.error.message);else onLoggedIn();setBusy(false)}
return <main className="login"><form className="login-card" onSubmit={submit}><div className="brand"><Bot size={30}/><div><strong>UzzapBot</strong><span>Control Center</span></div></div><h1>Administrator Login</h1><p>Sign in to monitor UzzapBot.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?"Signing in...":"Sign in"}</button></form></main>}

function App(){const[session,setSession]=useState<any>(null),[isAdmin,setIsAdmin]=useState(false),[page,setPage]=useState<Page>("dashboard"),[mobile,setMobile]=useState(false),[checking,setChecking]=useState(true);
useEffect(()=>{supabase.auth.getSession().then(async({data})=>{setSession(data.session);if(data.session){const a=await supabase.rpc("uzzapbot_is_admin");setIsAdmin(a.data===true)}setChecking(false)});const x=supabase.auth.onAuthStateChange(async(_e,s)=>{setSession(s);if(s){const a=await supabase.rpc("uzzapbot_is_admin");setIsAdmin(a.data===true)}else setIsAdmin(false)});return()=>x.data.subscription.unsubscribe()},[]);
if(checking)return <div className="loading">Loading...</div>;if(!session)return <Login onLoggedIn={()=>supabase.auth.getSession().then(({data})=>setSession(data.session))}/>;
if(!isAdmin)return <main className="login"><div className="login-card"><h1>Admin access required</h1><p>Your account is authenticated but is not assigned the UzzapBot admin role.</p><button className="primary" onClick={()=>supabase.auth.signOut()}>Sign out</button></div></main>;const title=nav.find(n=>n[0]===page)?.[1]||"Dashboard";
return <div className="app"><aside className={mobile?"sidebar open":"sidebar"}><div className="brand"><Bot size={28}/><div><strong>UzzapBot</strong><span>Control Center</span></div></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?"nav active":"nav"} onClick={()=>{setPage(id);setMobile(false)}}><Icon size={18}/>{label}</button>)}</nav><button className="nav logout" onClick={()=>supabase.auth.signOut()}><LogOut size={18}/>Logout</button></aside>{mobile&&<button className="backdrop" onClick={()=>setMobile(false)}><X/></button>}<section className="content"><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div><h1>{title}</h1><span>Production UzzapBot management</span></div><div className="online"><i/> Supabase</div></header>{page==="dashboard"&&<Dashboard/>}{page==="control"&&<Control/>}{page==="rooms"&&<Rooms/>}{page==="players"&&<Players/>}{page==="monitor"&&<Monitor/>}{page==="questions"&&<Questions/>}{page==="games"&&<Games/>}{page==="errors"&&<Errors/>}{page==="performance"&&<Performance/>}{page==="settings"&&<SettingsPage/>}</section></div>}

function Stat({label,value,icon:Icon}:{label:string;value:string;icon:any}){return <div className="card"><div className="card-icon"><Icon size={19}/></div><div><span>{label}</span><strong>{value}</strong></div></div>}
function Dashboard(){const[s,setS]=useState({processed:0,failed:0,games:0,players:0,latency:0,p95:0});const[events,setEvents]=useState<any[]>([]);const[activity,setActivity]=useState<any[]>([]);const[series,setSeries]=useState<any[]>([]);const load=async()=>{const [a,b,g,p,perf,msg]=await Promise.all([supabase.rpc("uzzapbot_cc_metrics"),supabase.rpc("uzzapbot_cc_events",{p_limit:8}),supabase.rpc("uzzapbot_cc_performance")]);setS({processed:a.data?.processed||0,failed:a.data?.failed||0,games:a.data?.games||0,players:a.data?.players||0,latency:Math.round(perf.data?.[0]?.avg_latency_ms||0),p95:Math.round(perf.data?.[0]?.p95_latency_ms||0)});setEvents(b.data||[]);setActivity((b.data||[]).slice(0,5));setSeries(Array.from({length:7},(_,i)=>{const d=new Date();d.setHours(d.getHours()-(6-i));return {hour:d.toLocaleTimeString([],{hour:"2-digit"}),events:(msg.data||[]).filter((x:any)=>new Date(x.received_at).getHours()===d.getHours()).length}}))};useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t)},[]);
return <><div className="hero-panel"><div><div className="eyebrow"><span className="pulse-dot"/> LIVE SYSTEM</div><h2>UzzapBot is running smoothly</h2><p>Production event processing is connected to Supabase and refreshing automatically.</p></div><div className="hero-meta"><strong>{s.latency} ms</strong><span>avg response</span></div></div><div className="toolbar"><div><h2>Overview</h2><p>Live production health and activity.</p></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div><div className="grid"><Stat label="Bot Runtime" value="Healthy" icon={Bot}/><Stat label="Processed Events" value={String(s.processed)} icon={Activity}/><Stat label="Failed Events" value={String(s.failed)} icon={AlertTriangle}/><Stat label="Game Sessions" value={String(s.games)} icon={Gamepad2}/><Stat label="Players" value={String(s.players)} icon={Users}/><Stat label="P95 Latency" value={s.p95+" ms"} icon={Gauge}/></div><div className="dashboard-columns"><div className="panel chart-panel"><div className="panel-heading"><div><h2>Event activity</h2><p>Recent event volume across the control center.</p></div><span className="live-chip">● LIVE</span></div><div className="mini-chart">{series.map((x,i)=><div className="bar-wrap" key={i}><div className="bar" style={{height:Math.max(12,Math.min(100,x.events*22+18))+"%"}}/><span>{x.hour}</span></div>)}</div></div><div className="panel"><div className="panel-heading"><div><h2>Live activity</h2><p>Latest bot events.</p></div></div><div className="activity-list">{activity.map((x:any)=><div className="activity-row" key={x.message_id}><span className={"activity-dot "+x.status}/><div><strong>Message #{x.message_id}</strong><small>{x.status} · {new Date(x.received_at).toLocaleTimeString()}</small></div><b>{x.processed_at?Math.max(0,new Date(x.processed_at).getTime()-new Date(x.received_at).getTime())+" ms":"—"}</b></div>)}</div></div></div><RecentEvents/></>}

function RecentEvents(){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.rpc("uzzapbot_cc_events",{p_limit:12}).then(({data})=>setRows(data||[]))},[]);return <div className="panel"><h2>Recent Bot Events</h2><div className="table-wrap"><table><thead><tr><th>ID</th><th>Received</th><th>Status</th><th>Latency</th><th>Error</th></tr></thead><tbody>{rows.map(r=><tr key={r.message_id}><td>{r.message_id}</td><td>{new Date(r.received_at).toLocaleString()}</td><td><b className={"badge "+r.status}>{r.status}</b></td><td>{r.processed_at?String(Math.max(0,new Date(r.processed_at).getTime()-new Date(r.received_at).getTime()))+" ms":"-"}</td><td>{r.error_text||"-"}</td></tr>)}{!rows.length&&<tr><td colSpan={5}>No events found.</td></tr>}</tbody></table></div></div>}

function Monitor(){const[rows,setRows]=useState<any[]>([]);const load=async()=>{const r=await supabase.rpc("uzzapbot_cc_commands",{p_limit:100});setRows(r.data||[])};useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);return <div className="panel"><div className="toolbar"><div><h2>Live Command Activity</h2><p>Messages received by UzzapBot with processing status and latency.</p></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div><div className="table-wrap"><table><thead><tr><th>ID</th><th>Room</th><th>Sender</th><th>Command / Message</th><th>Status</th><th>Latency</th><th>Time</th></tr></thead><tbody>{rows.map(r=><tr key={r.message_id}><td>{r.message_id}</td><td>{r.room_name}</td><td>{r.sender||"-"}</td><td className="command-cell">{r.body}</td><td><b className={"badge "+r.status}>{r.status}</b></td><td>{r.latency_ms!=null?r.latency_ms+" ms":"-"}</td><td>{new Date(r.received_at).toLocaleString()}</td></tr>)}{!rows.length&&<tr><td colSpan={7}>No bot events found.</td></tr>}</tbody></table></div></div>}
function Questions(){
 const[stats,setStats]=useState<Record<number,any>>({});
 const loadStats=async()=>{const r=await supabase.rpc("uzzapbot_cc_question_stats");const map:any={};(r.data||[]).forEach((x:any)=>map[x.question_id]=x);setStats(map)};

 const[rows,setRows]=useState<any[]>([]),[busy,setBusy]=useState(true),[form,setForm]=useState({category:"trivia",question:"",answer:"",aliases:"",points:"10",difficulty:"normal"}),[msg,setMsg]=useState("");
 const load=async()=>{setBusy(true);const r=await supabase.from("uzzapbot_questions").select("*").order("created_at",{ascending:false}).limit(100);setRows(r.data||[]);setBusy(false)};useEffect(()=>{load()},[]);
 const add=async(e:React.FormEvent)=>{e.preventDefault();setMsg("");const aliases=form.aliases.split(",").map(x=>x.trim()).filter(Boolean);const v=await supabase.rpc("uzzapbot_question_validation",{p_question:form.question.trim(),p_answer:form.answer.trim(),p_aliases:aliases,p_category:form.category});if(v.error){setMsg(v.error.message);return}const check=v.data as any;const r=await supabase.from("uzzapbot_questions").insert({category:form.category,question:form.question.trim(),answer:form.answer.trim(),aliases,points:Number(form.points),difficulty:form.difficulty,status:"draft",created_by:(await supabase.auth.getUser()).data.user?.id,verification_score:check?.score??0,duplicate_of:check?.duplicate_of??null,verification_notes:(check?.issues||[]).join("; ")});if(r.error)setMsg(r.error.message);else{setMsg("Draft saved. Verification: "+(check?.score??0)+"/100"+((check?.issues||[]).length?" — "+check.issues.join("; "):"."));setForm({...form,question:"",answer:"",aliases:""});load()}};
 const setStatus=async(id:number,status:string)=>{const{data:{user}}=await supabase.auth.getUser();const r=await supabase.from("uzzapbot_questions").update({status,reviewed_by:user?.id||null,reviewed_at:status==="approved"||status==="rejected"?new Date().toISOString():null}).eq("id",id);if(r.error)setMsg(r.error.message);else load()};
 return <><div className="panel"><div className="toolbar"><div><h2>Question Bank</h2><p>Admin-managed questions with verification status.</p></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div><form className="question-form" onSubmit={add}><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>trivia</option><option>anime</option><option>logic</option><option>gta</option><option>english</option><option>tagalog</option><option>math</option></select><input placeholder="Question" value={form.question} onChange={e=>setForm({...form,question:e.target.value})} required/><input placeholder="Correct answer" value={form.answer} onChange={e=>setForm({...form,answer:e.target.value})} required/><input placeholder="Aliases, comma separated" value={form.aliases} onChange={e=>setForm({...form,aliases:e.target.value})}/><input type="number" min="1" max="1000" value={form.points} onChange={e=>setForm({...form,points:e.target.value})}/><select value={form.difficulty} onChange={e=>setForm({...form,difficulty:e.target.value})}><option>easy</option><option>normal</option><option>hard</option></select><button className="primary" type="submit">Add Draft</button></form>{msg&&<div className="notice">{msg}</div>}</div><div className="panel"><h2>Verification Queue</h2>{busy?<p>Loading...</p>:<div className="table-wrap"><table><thead><tr><th>Category</th><th>Question</th><th>Answer</th><th>Difficulty</th><th>Score</th><th>Uses</th><th>Correct</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(q=><tr key={q.id}><td>{q.category}</td><td>{q.question}</td><td>{q.answer}</td><td>{q.difficulty}</td><td>{q.verification_score??"-"}/100{q.duplicate_of?" · duplicate #"+q.duplicate_of:""}</td><td>{stats[q.id]?.uses??0}</td><td>{stats[q.id]?.correct??0}</td><td><b className={"badge "+(q.status==="approved"?"processed":q.status==="rejected"?"failed":"received")}>{q.status}</b></td><td><div className="actions">{q.status!=="approved"&&<button className="mini approve" onClick={()=>setStatus(q.id,"approved")}>Approve</button>}{q.status!=="rejected"&&<button className="mini reject" onClick={()=>setStatus(q.id,"rejected")}>Reject</button>}</div></td></tr>)}{!rows.length&&<tr><td colSpan={9}>No questions yet.</td></tr>}</tbody></table></div>}</div></>
}
function Games(){const[games,setGames]=useState<any[]>([]);const load=async()=>{const r=await supabase.rpc("uzzapbot_cc_games",{p_limit:50});setGames(r.data||[])};useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t)},[]);return <div className="panel"><div className="toolbar"><div><h2>Game Sessions</h2><p>Live game state and player counts.</p></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div><div className="table-wrap"><table><thead><tr><th>Room</th><th>Game</th><th>Mode</th><th>Q#</th><th>Points</th><th>Limit</th><th>Players</th><th>Paused</th><th>Updated</th></tr></thead><tbody>{games.map(g=><tr key={g.room_name}><td>{g.room_name}</td><td>{g.game}</td><td>{g.mode}</td><td>{g.question_number}</td><td>{g.points}</td><td>{g.limit_count}</td><td>{g.players}</td><td>{g.paused?"Yes":"No"}</td><td>{new Date(g.updated_at).toLocaleString()}</td></tr>)}{!games.length&&<tr><td colSpan={9}>No active game sessions found.</td></tr>}</tbody></table></div></div>}
function Performance(){const[p,setP]=useState<any>(null),[q,setQ]=useState<any>(null);const load=async()=>{const a=await supabase.rpc("uzzapbot_cc_performance");const b=await supabase.rpc("uzzapbot_cc_question_stats");setP(a.data?.[0]||null);const rows=b.data||[];setQ({total:rows.reduce((x:any,r:any)=>x+Number(r.uses||0),0),correct:rows.reduce((x:any,r:any)=>x+Number(r.correct||0),0),questions:rows.length,used:rows.filter((r:any)=>Number(r.uses||0)>0).length})};useEffect(()=>{load()},[]);return <div><div className="toolbar"><div><h2>Bot Performance</h2><p>Production event and question metrics for the last 24 hours.</p></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div><div className="grid">{<Stat label="Processed" value={String(p?.processed??0)} icon={Activity}/>}<Stat label="Failed" value={String(p?.failed??0)} icon={AlertTriangle}/><Stat label="Avg Latency" value={(p?.avg_latency_ms??0)+" ms"} icon={Clock}/><Stat label="P95 Latency" value={(p?.p95_latency_ms??0)+" ms"} icon={Gauge}/><Stat label="Question Uses" value={String(q?.total??0)} icon={HelpCircle}/><Stat label="Questions Used" value={String(q?.used??0)+"/"+String(q?.questions??0)} icon={BookOpen}/></div><div className="panel"><h2>Last Bot Activity</h2><p>{p?.last_processed_at?new Date(p.last_processed_at).toLocaleString():"No processed events in the last 24 hours."}</p></div></div>}

function Errors(){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.rpc("uzzapbot_cc_events",{p_limit:200}).then(({data})=>setRows((data||[]).filter((x:any)=>x.status==="failed")))},[]);return <div className="panel"><h2>Error Center</h2><p>Failed production events. The dashboard does not automatically retry events.</p><div className="table-wrap"><table><thead><tr><th>Message ID</th><th>Time</th><th>Error</th></tr></thead><tbody>{rows.map(r=><tr key={r.message_id}><td>{r.message_id}</td><td>{new Date(r.received_at).toLocaleString()}</td><td>{r.error_text||"Unknown error"}</td></tr>)}{!rows.length&&<tr><td colSpan={3}>No failed events.</td></tr>}</tbody></table></div></div>}
function SettingsPage(){
 const[settings,setSettings]=useState<any>({}),[audit,setAudit]=useState<any[]>([]),[busy,setBusy]=useState(true);
 const load=async()=>{setBusy(true);const s=await supabase.from("uzzapbot_control_settings").select("*");const m:any={};(s.data||[]).forEach((x:any)=>m[x.key]=x.value);setSettings(m);const a=await supabase.from("uzzapbot_audit_log").select("*").order("created_at",{ascending:false}).limit(30);setAudit(a.data||[]);setBusy(false)};
 useEffect(()=>{load()},[]);
 const save=async(key:string,value:any)=>{const{data:{user}}=await supabase.auth.getUser();const r=await supabase.from("uzzapbot_control_settings").upsert({key,value,updated_by:user?.id,updated_at:new Date().toISOString()});if(!r.error)await supabase.rpc("uzzapbot_audit",{action:"settings.update",target_type:"setting",target_id:key,details:{value}});load()};
 return <div><div className="panel"><div className="toolbar"><div><h2>Bot Settings</h2><p>Administrative controls stored in Supabase.</p></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div><div className="settings"><label>Bot enabled <input type="checkbox" checked={settings.bot_enabled?.enabled??true} onChange={e=>save("bot_enabled",{enabled:e.target.checked})}/></label><label>Maintenance mode <input type="checkbox" checked={settings.maintenance?.enabled??false} onChange={e=>save("maintenance",{enabled:e.target.checked})}/></label><label>Default points <input type="number" min="1" max="1000" value={settings.default_points?.value??10} onChange={e=>save("default_points",{value:Number(e.target.value)||10})}/></label><label>Default limit <input type="number" min="1" value={settings.default_limit?.value??100} onChange={e=>save("default_limit",{value:Number(e.target.value)||100})}/></label></div></div><div className="panel"><h2>Audit Log</h2>{busy?<p>Loading...</p>:audit.length===0?<p>No audit entries yet.</p>:<div className="table-wrap"><table><thead><tr><th>Action</th><th>Target</th><th>Time</th></tr></thead><tbody>{audit.map((x:any)=><tr key={x.id}><td>{x.action}</td><td>{x.target_id||"-"}</td><td>{new Date(x.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>}</div></div>}

function Control(){
 const[games,setGames]=useState<any[]>([]),[room,setRoom]=useState(""),[mode,setMode]=useState("TRIVIA"),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const load=async()=>{const r=await supabase.rpc("uzzapbot_cc_games",{p_limit:100});setGames(r.data||[]);if(!room&&r.data?.[0]?.room_name)setRoom(r.data[0].room_name)};
 useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);
 const command=async(cmd:string)=>{if(!room)return;setBusy(true);setMsg("");const r=await supabase.rpc("uzzapbot_issue_command",{p_room_name:room,p_command:cmd});setMsg(r.error?r.error.message:"Command queued: "+cmd);setBusy(false);load()};
 const start=()=>command("/"+mode+" ON");
 return <div><div className="toolbar"><div><h2>Game Control</h2><p>Send authenticated admin commands to the live UzzapBot in a room.</p></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div>
 <div className="control-toolbar"><select value={room} onChange={e=>setRoom(e.target.value)}><option value="">Select room</option>{games.map(g=><option key={g.room_name}>{g.room_name}</option>)}</select><select value={mode} onChange={e=>setMode(e.target.value)}>{["TRIVIA","MATH","ANIME","LOGIC","ALGEBRA","PH"].map(x=><option key={x}>{x}</option>)}</select><button className="primary" disabled={!room||busy} onClick={start}>Start {mode}</button></div>
 {msg&&<div className="notice">{msg}</div>}
 <div className="control-grid">{games.map(g=><div className="panel game-card" key={g.room_name}><div className="game-head"><div><span className="eyebrow dark">ROOM</span><h2>{g.room_name}</h2></div><b className={g.paused?"badge received":"status-online"}>{g.paused?"PAUSED":"LIVE"}</b></div><div className="game-metrics"><div><span>Game</span><strong>{g.game||"—"}</strong></div><div><span>Question</span><strong>#{g.question_number||0}</strong></div><div><span>Points</span><strong>{g.points||0}</strong></div><div><span>Players</span><strong>{g.players||0}</strong></div></div><div className="control-actions"><button className="mini" onClick={()=>{setRoom(g.room_name);command("/PAUSE")}}>Pause</button><button className="mini" onClick={()=>{setRoom(g.room_name);command("/RESUME")}}>Resume</button><button className="mini" onClick={()=>{setRoom(g.room_name);command("/NEXT")}}>Next</button><button className="mini" onClick={()=>{setRoom(g.room_name);command("/CLUE")}}>Clue</button><button className="mini" onClick={()=>{setRoom(g.room_name);command("/REPOST")}}>Repost</button><button className="mini" onClick={()=>{setRoom(g.room_name);command("/REVEAL")}}>Reveal</button><button className="mini reject" onClick={()=>{setRoom(g.room_name);command("/STOP")}}>Stop</button></div></div>)}</div></div>
}
function Rooms(){
 const[rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[msg,setMsg]=useState("");
 const load=async()=>{const r=await supabase.rpc("uzzapbot_control_rooms");setRows(r.data||[]);if(!selected&&r.data?.[0])setSelected(r.data[0]);else if(selected){const n=(r.data||[]).find((x:any)=>x.room_name===selected.room_name);if(n)setSelected(n)}};
 useEffect(()=>{load()},[]);
 const save=async()=>{if(!selected)return;const r=await supabase.rpc("uzzapbot_set_room_control",{p_room_name:selected.room_name,p_activated:selected.activated,p_locked:selected.locked,p_wcbot:selected.wcbot,p_welcome_message:selected.welcome_message,p_challenge_room:selected.challenge_room,p_activity_enabled:selected.activity_enabled});setMsg(r.error?r.error.message:"Room settings saved.");load()};
 return <div><div className="toolbar"><div><h2>Room Control</h2><p>Activation, locking, welcome bot, challenge room and automatic activity controls.</p></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div><div className="room-layout"><div className="panel room-list"><h2>Rooms</h2>{rows.map(r=><button key={r.room_name} className={selected?.room_name===r.room_name?"room-item active":"room-item"} onClick={()=>setSelected(r)}><span>{r.room_name}</span><small>{r.activated?"Activated":"Inactive"} · {r.locked?"Locked":"Unlocked"}</small></button>)}</div>{selected&&<div className="panel room-editor"><div className="toolbar"><div><h2>{selected.room_name}</h2><p>Live room configuration</p></div><b className={selected.activated?"status-online":"status-offline"}>{selected.activated?"ACTIVE":"INACTIVE"}</b></div><div className="settings"><label>Bot activated <input type="checkbox" checked={!!selected.activated} onChange={e=>setSelected({...selected,activated:e.target.checked})}/></label><label>Room locked <input type="checkbox" checked={!!selected.locked} onChange={e=>setSelected({...selected,locked:e.target.checked})}/></label><label>Welcome Bot <input type="checkbox" checked={!!selected.wcbot} onChange={e=>setSelected({...selected,wcbot:e.target.checked})}/></label><label>Automatic activity <input type="checkbox" checked={!!selected.activity_enabled} onChange={e=>setSelected({...selected,activity_enabled:e.target.checked})}/></label></div><label className="field">Welcome message<input value={selected.welcome_message||""} onChange={e=>setSelected({...selected,welcome_message:e.target.value})} placeholder="welcome to {room} {nickname}"/></label><label className="field">Challenge room<input value={selected.challenge_room||""} onChange={e=>setSelected({...selected,challenge_room:e.target.value})} placeholder="Optional mirror/challenge room"/></label><div className="room-meta"><span>Activity: <b>{selected.activity_state||"INACTIVE"}</b></span><span>Last human: {selected.last_human_activity_at?new Date(selected.last_human_activity_at).toLocaleString():"—"}</span><span>Last bot: {selected.last_bot_activity_at?new Date(selected.last_bot_activity_at).toLocaleString():"—"}</span></div>{msg&&<div className="notice">{msg}</div>}<button className="primary" onClick={save}>Save room controls</button></div>}</div></div>
}
function Players(){
 const[rooms,setRooms]=useState<any[]>([]),[room,setRoom]=useState(""),[players,setPlayers]=useState<any[]>([]);
 useEffect(()=>{supabase.rpc("uzzapbot_control_rooms").then(({data})=>{setRooms(data||[]);if(data?.[0])setRoom(data[0].room_name)})},[]);
 useEffect(()=>{if(!room){setPlayers([]);return}supabase.rpc("uzzapbot_control_players",{p_room_name:room}).then(({data})=>setPlayers(data||[]))},[room]);
 return <div><div className="toolbar"><div><h2>Players</h2><p>Current game participants, scores and answer activity.</p></div><select value={room} onChange={e=>setRoom(e.target.value)}>{rooms.map(r=><option key={r.room_name}>{r.room_name}</option>)}</select></div><div className="panel"><div className="table-wrap"><table><thead><tr><th>Username</th><th>Nickname</th><th>Score</th><th>Correct</th><th>Attempts</th><th>Clues</th><th>Joined</th><th>Updated</th></tr></thead><tbody>{players.map(p=><tr key={p.username}><td>{p.username}</td><td>{p.nickname}</td><td><b>{p.score}</b></td><td>{p.correct}</td><td>{p.attempts}</td><td>{p.clues_used}</td><td>{new Date(p.joined_at).toLocaleString()}</td><td>{new Date(p.updated_at).toLocaleString()}</td></tr>)}{!players.length&&<tr><td colSpan={8}>No active players in this room.</td></tr>}</tbody></table></div></div></div>
}
\nexport default App;
